### ISSUE TITLE
New release with updated dependencies?

### ISSUE THREAD

**Issue by shanike** [ej-shafran/eslint-plugin-nestjs-pedantic#224]
Hi! I see the dependencies in the codebase have up-to-date dependencies, unlike the package released to npm (v0.0.4).  
Can you please release to npm a version with updated dependencies?

---
I'm getting a classic peer dependency issue in my project:

In my projects's package.json I have `"eslint": "^9.16.0"`  
But eslint-plugin-nestjs-pedantic has `"@typescript-eslint/utils": "^7.0.1"` which requires `eslint@^8.56.0`
<details>
<summary>node_modules / eslint-plugin-nestjs-pedantic / package.json</summary>

```jsonc
{
  "$schema": "https://json.schemastore.org/package.json",
  "name": "eslint-plugin-nestjs-pedantic",
  "version": "0.0.4",
  "description": "An ESLint plugin for NestJS, with pedantic rules",
  // ...
  "dependencies": {
    "@typescript-eslint/utils": "^7.0.1"
  },
  // ...
}
```
</details>

The peer dependency issue can be seen below:
![image](https://github.com/user-attachments/assets/5488ba46-98ae-4a01-a7a6-b382f447e28a)
```
└─┬ eslint-plugin-nestjs-pedantic 0.0.4
  └─┬ @typescript-eslint/utils 7.18.0
    └── ✕ unmet peer eslint@^8.56.0: found 9.16.0
```
Thanks!

**Comment by ej-shafran** [comment]
Yeah, I've been wanting to do an update of this package to eslint v9
